import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireUser } from "@/lib/auth";
type State = { students: any[]; teachers: any[]; courses: any[]; enrollments: any[]; expenses: any[]; payments: any[]; sessions: any[]; payouts: any[]; rooms: any[]; attendances: any[] };
const emptyState: State = { students: [], teachers: [], courses: [], enrollments: [], expenses: [], payments: [], sessions: [], payouts: [], rooms: [], attendances: [] };

async function writeState(tx: any, state: State) {
  await tx.attendance.deleteMany(); await tx.enrollment.deleteMany(); await tx.payment.deleteMany(); await tx.payout.deleteMany(); await tx.session.deleteMany(); await tx.packSubject.deleteMany(); await tx.course.deleteMany(); await tx.expense.deleteMany(); await tx.room.deleteMany(); await tx.student.deleteMany(); await tx.teacher.deleteMany();
  for (const teacher of state.teachers) await tx.teacher.create({ data: { id: teacher.id, name: teacher.name, specialty: teacher.specialty, commission: teacher.commission } });
  for (const course of state.courses) { const teacher = state.teachers.find(item => item.name === course.teacher); await tx.course.create({ data: { id: course.id, name: course.name, type: course.type, price: course.price, teacherId: teacher?.id } }); }
  for (const pack of state.courses.filter(item => item.type === "باقة")) for (const subjectId of pack.subjectIds || []) await tx.packSubject.create({ data: { packId: pack.id, subjectId } });
  for (const student of state.students) await tx.student.create({ data: { id: student.id, name: student.name, phone: student.phone, whatsapp: student.whatsapp, status: student.status, due: student.due, lastPayment: student.lastPayment, enrollmentDate: student.enrollmentDate, enrollmentFee: student.enrollmentFee || 0, subscriptionYear: student.subscriptionYear } });
  for (const enrollment of state.enrollments) await tx.enrollment.create({ data: { id: enrollment.id, studentId: enrollment.studentId, courseId: enrollment.courseId, enrolledAt: enrollment.enrolledAt, removedAt: enrollment.removedAt, status: enrollment.status, source: enrollment.source } });
  for (const payment of state.payments) await tx.payment.create({ data: { id: payment.id, studentId: payment.studentId, amount: payment.amount, totalAmount: payment.totalAmount, month: payment.month, status: payment.status, date: payment.date, method: payment.method, receiptNumber: payment.receiptNumber } });
  for (const expense of state.expenses) await tx.expense.create({ data: { id: expense.id, title: expense.title, category: expense.category, amount: expense.amount, date: expense.date } });
  for (const room of state.rooms || []) await tx.room.create({ data: { id: room.id, name: room.name } });
  for (const session of state.sessions) { const teacher = state.teachers.find(item => item.name === session.teacher); const course = state.courses.find(item => item.name === session.course); await tx.session.create({ data: { id: session.id, title: session.title, teacherId: teacher?.id, courseId: course?.id, date: session.date, weekday: session.weekday, time: session.time, endTime: session.endTime, room: session.room } }); }
  for (const attendance of state.attendances || []) await tx.attendance.create({ data: { id: attendance.id, sessionId: attendance.sessionId, studentId: attendance.studentId, occurrenceDate: attendance.occurrenceDate, status: attendance.status } });
  for (const payout of state.payouts) await tx.payout.create({ data: { id: payout.id, teacherId: payout.teacherId, month: payout.month, studentCount: payout.studentCount, revenue: payout.revenue, commission: payout.commission, amount: payout.amount, status: payout.status, paidAt: payout.paidAt } });
}

async function readState(): Promise<State> {
  const [students, teachers, courses, packSubjects, enrollments, payments, expenses, sessions, payouts, rooms] = await Promise.all([prisma.student.findMany(), prisma.teacher.findMany(), prisma.course.findMany({ include: { teacher: true } }), prisma.packSubject.findMany(), prisma.enrollment.findMany(), prisma.payment.findMany(), prisma.expense.findMany(), prisma.session.findMany({ include: { teacher: true, course: true } }), prisma.payout.findMany({ include: { teacher: true } }), prisma.room.findMany()]);
  const expandedCourseIds = (courseId: number) => { const course = courses.find(item => item.id === courseId); return course?.type === "باقة" ? packSubjects.filter(link => link.packId === courseId).map(link => link.subjectId) : [courseId]; };
  const attendances = await prisma.attendance.findMany();
  return { students, teachers: teachers.map(teacher => ({ ...teacher, students: new Set(enrollments.filter(item => item.status === "نشط" && expandedCourseIds(item.courseId).some(id => courses.some(course => course.id === id && course.teacherId === teacher.id))).map(item => item.studentId)).size, sessions: sessions.filter(session => session.teacherId === teacher.id).length })), courses: courses.map(course => ({ ...course, teacher: course.teacher?.name || "", subjectIds: packSubjects.filter(link => link.packId === course.id).map(link => link.subjectId), enrolled: enrollments.filter(item => item.courseId === course.id && item.status === "نشط").length })), enrollments, payments: payments.map(payment => ({ ...payment, student: students.find(student => student.id === payment.studentId)?.name || "" })), expenses, sessions: sessions.map(session => ({ ...session, teacher: session.teacher?.name || "", course: session.course?.name || "" })), payouts: payouts.map(payout => ({ ...payout, teacher: payout.teacher.name, teacherId: payout.teacherId })), rooms, attendances };
}

export async function GET() { try { const user = await requireUser(); const state = await readState(); if (user.role === "ADMIN") return NextResponse.json({ ...state, expenses: [], payouts: [] }); return NextResponse.json(state); } catch (error) { console.error(error); return NextResponse.json({ error: error instanceof Error && error.message === "UNAUTHORIZED" ? "Unauthorized" : "Unable to load database state" }, { status: error instanceof Error && error.message === "UNAUTHORIZED" ? 401 : 500 }); } }
export async function PUT(request: Request) { try { const user = await requireUser(); const data = await request.json() as State; if (user.role === "ADMIN") { const existing = await readState(); data.expenses = existing.expenses; data.payouts = existing.payouts; } await prisma.$transaction(tx => writeState(tx, data)); return NextResponse.json(await readState()); } catch (error) { console.error(error); return NextResponse.json({ error: error instanceof Error && error.message === "UNAUTHORIZED" ? "Unauthorized" : "Unable to save relational database state" }, { status: error instanceof Error && error.message === "UNAUTHORIZED" ? 401 : 500 }); } }
