"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import { Bell, BookOpen, CalendarDays, ChevronDown, ChevronLeft, CircleDollarSign, ClipboardList, GraduationCap, LayoutDashboard, Menu, Search, Settings, Users, WalletCards, X } from "lucide-react";
import { getLanguageConfig, getTranslations, useLanguage } from "@/components/language-provider";
import { useAuth } from "@/components/auth-provider";

const navItems = [["الرئيسية", "/", LayoutDashboard], ["الطلاب", "/students", Users], ["الأساتذة", "/teachers", GraduationCap], ["الدورات", "/courses", BookOpen], ["التسجيلات", "/registrations", ClipboardList, [["كل التسجيلات", "/registrations"], ["الدفوعات الشهرية", "/payments"]]], ["الجدول", "/schedule", CalendarDays, [["جدول الحصص", "/schedule"], ["تسجيل الحضور", "/attendance"]]], ["المصاريف", "/expenses", WalletCards], ["الطلاب المتأخرون", "/late-students", Bell], ["رواتب الأساتذة", "/payouts", CircleDollarSign], ["الإعدادات", "/settings", Settings]] as const;

export function CentmanShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const { language } = useLanguage();
  const t = getTranslations(language);
  const { user } = useAuth();
  const [open, setOpen] = useState(false);
  const [expanded, setExpanded] = useState<string | null>("التسجيلات");
  const [todayLabel, setTodayLabel] = useState("");
  const [logo, setLogo] = useState("");
  const [institutionName, setInstitutionName] = useState("CentMan");
  const labels: Record<string, string> = { "الرئيسية": t.home, "الطلاب": t.students, "الأساتذة": t.teachers, "الدورات": t.courses, "التسجيلات": t.registrations, "الجدول": t.schedule, "المصاريف": t.expenses, "الطلاب المتأخرون": t.lateStudents, "رواتب الأساتذة": t.payouts, "الإعدادات": t.settings };
  useEffect(() => { setTodayLabel(new Intl.DateTimeFormat(getLanguageConfig(language).locale, { dateStyle: "full" }).format(new Date())); }, [language]);
  useEffect(() => { fetch("/api/settings", { cache: "no-store" }).then(response => response.ok ? response.json() : Promise.reject(new Error("settings"))).then(settings => { setLogo(settings.logo || ""); setInstitutionName(settings.name || "CentMan"); }).catch(() => { setLogo(""); setInstitutionName("CentMan"); }); }, []);
  const visibleNavItems = user?.role === "ADMIN" ? navItems.filter(([label]) => !["المصاريف", "الطلاب المتأخرون", "رواتب الأساتذة"].includes(label)) : navItems;
  return <main className="min-h-screen bg-[#f5f7f6]">
    {open && <button aria-label="إغلاق القائمة" className="fixed inset-0 z-20 bg-[#15231d]/30 lg:hidden" onClick={() => setOpen(false)} />}
    <aside className={`fixed top-0 z-30 flex h-screen max-h-screen w-[270px] flex-col overflow-y-auto overscroll-contain border-[#e3eae5] bg-white px-4 py-5 transition-transform ltr:border-r rtl:border-l lg:translate-x-0 ${open ? "translate-x-0" : "ltr:-translate-x-full rtl:translate-x-full"}`}>
      <div className="mb-9 flex shrink-0 items-center justify-between px-3"><Link href="/" className="flex items-center gap-3"><span className={`flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl text-xl font-bold ${logo ? "bg-transparent" : "bg-[#e4e8fd] text-[#5054c0]"}`}>{logo ? <img src={logo} alt="شعار المؤسسة" className="h-full w-full object-contain" /> : "C"}</span><span><span className="block max-w-[150px] truncate text-lg font-black text-[#5054c0]">{institutionName}</span><span className="block text-[10px] text-[#85968d]">{language === "العربية" ? "إدارة مركز التعليم" : language === "Français" ? "Gestion du centre" : "Education center management"}</span></span></Link><button className="text-[#84938b] lg:hidden" onClick={() => setOpen(false)}><X size={19} /></button></div>
      <div className="mb-4 shrink-0 px-3 text-[10px] font-bold tracking-[0.18em] text-[#a0afa7]">{language === "العربية" ? "القائمة الرئيسية" : language === "Français" ? "MENU PRINCIPAL" : "MAIN MENU"}</div>
      <nav className="shrink-0 space-y-1">{visibleNavItems.map(([label, href, Icon, children]) => { const active = href === "/" ? pathname === "/" : pathname.startsWith(href); return <div key={label}><div className={`flex items-center rounded-xl ${active ? "bg-[#e6f5ee] text-[#008a55]" : "text-[#697b70] hover:bg-[#f2f7f4]"}`}><Link href={href} onClick={() => setOpen(false)} className="flex flex-1 items-center gap-3 px-3 py-3 text-right text-[13px] font-bold"><Icon size={18} /><span>{labels[label]}</span></Link>{children && <button aria-label={`فتح ${labels[label]}`} onClick={() => setExpanded(expanded === label ? null : label)} className="px-3"><ChevronDown size={15} className={`transition-transform ${expanded === label ? "rotate-180" : ""}`} /></button>}</div>{children && expanded === label && <div className="mr-10 mt-1 space-y-1 border-r border-[#dcebe3] pr-3">{children.map(([child, childHref]) => <Link key={child} href={childHref} onClick={() => setOpen(false)} className="block py-2 text-right text-xs text-[#84938b] hover:text-[#008a55]">{child}</Link>)}</div>}</div>; })}</nav>
      <div className="mt-auto shrink-0 rounded-2xl bg-[#f2f8f4] p-4"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-bold text-[#365349]">{user?.name || "CentMan"}</span><span className="text-[10px] font-bold text-[#00a060]">{user?.role === "SUPER_ADMIN" ? "Super-admin" : "Admin"}</span></div><button onClick={async () => { await fetch("/api/auth/logout", { method: "POST" }); window.location.href = "/login"; }} className="mt-3 text-[11px] font-bold text-[#c4584e]">تسجيل الخروج</button></div>
    </aside>
    <section className="min-h-screen ltr:lg:ml-[270px] rtl:lg:mr-[270px]"><header className="sticky top-0 z-10 flex h-[76px] items-center justify-between border-b border-[#e3eae5] bg-[#f5f7f6]/95 px-5 backdrop-blur md:px-9"><div className="flex items-center gap-4"><button aria-label="فتح القائمة" className="text-[#597067] lg:hidden" onClick={() => setOpen(true)}><Menu size={22} /></button><div className="text-xs font-bold text-[#9aa9a1]">{todayLabel}</div></div><div className="flex items-center gap-3"><div className="hidden h-10 w-52 items-center gap-2 rounded-xl border border-[#e1e9e4] bg-white px-3 text-[#a0afa7] md:flex"><Search size={17} /><input aria-label="بحث" className="w-full bg-transparent text-xs outline-none" placeholder={t.search} /></div><button aria-label="الإشعارات" className="relative rounded-xl border border-[#e1e9e4] bg-white p-2.5 text-[#71857a]"><Bell size={18} /></button><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#d8eee3] text-sm font-black text-[#008a55]">أح</div></div></header><div className="grid-paper min-h-[calc(100vh-76px)] px-5 py-7 md:px-9">{children}</div></section>
  </main>;
}

export function PageTitle({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: React.ReactNode }) { const { language } = useLanguage(); const titleMap: Record<string, [string, string, string]> = { "الطلاب": ["الطلاب", "Étudiants", "Students"], "الأساتذة": ["الأساتذة", "Enseignants", "Teachers"], "المواد والباقات": ["المواد والباقات", "Matières et packs", "Subjects and packs"], "التسجيلات والدفوعات": ["التسجيلات والدفوعات", "Inscriptions et paiements", "Registrations and payments"], "الدفوعات الشهرية": ["الدفوعات الشهرية", "Paiements mensuels", "Monthly payments"], "المصاريف": ["المصاريف", "Dépenses", "Expenses"], "الطلاب المتأخرون": ["الطلاب المتأخرون", "Étudiants en retard", "Late students"], "رواتب الأساتذة": ["رواتب الأساتذة", "Paiements enseignants", "Teacher payouts"], "الجدول الزمني": ["الجدول الزمني", "Planning", "Schedule"], "تسجيل الحضور": ["تسجيل الحضور", "Présences", "Attendance"], "الإعدادات": ["الإعدادات", "Paramètres", "Settings"] }; const translatedTitle = titleMap[title]?.[language === "العربية" ? 0 : language === "Français" ? 1 : 2] || title; return <div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div>{eyebrow && <p className="mb-1 text-xs font-bold text-[#00a060]">{eyebrow}</p>}<h2 className="text-2xl font-black tracking-tight text-[#17251f]">{translatedTitle}</h2></div>{action}</div>; }
export function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <div className={`rounded-2xl border border-[#e3eae5] bg-white p-5 shadow-[0_4px_18px_rgba(28,67,47,0.04)] ${className}`}>{children}</div>; }
export function Button({ children, onClick, variant = "primary", type = "button", disabled = false, form }: { children: React.ReactNode; onClick?: () => void; variant?: "primary" | "outline" | "danger"; type?: "button" | "submit"; disabled?: boolean; form?: string }) { return <button type={type} form={form} onClick={onClick} disabled={disabled} className={`rounded-xl px-4 py-2.5 text-xs font-bold transition-colors disabled:cursor-not-allowed disabled:opacity-50 ${variant === "primary" ? "bg-[#00a060] text-white hover:bg-[#008a55]" : variant === "danger" ? "bg-[#fff0ee] text-[#c4584e] hover:bg-[#ffe5e1]" : "border border-[#dbe7df] bg-white text-[#53685d] hover:bg-[#f2f7f4]"}`}>{children}</button>; }
export function Toast({ message }: { message: string }) { return message ? <div className="fixed bottom-6 left-6 z-50 rounded-xl bg-[#17251f] px-5 py-3 text-xs font-bold text-white shadow-xl">{message}</div> : null; }
export function ConfirmDialog({ title, message, confirmLabel = "حذف", onConfirm, onCancel }: { title: string; message: string; confirmLabel?: string; onConfirm: () => void; onCancel: () => void }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#292929]/35 p-4"><div role="alertdialog" aria-modal="true" className="w-full max-w-sm rounded-2xl bg-white p-6 text-right shadow-2xl"><h3 className="text-lg font-black text-[#292929]">{title}</h3><p className="mt-3 text-sm leading-6 text-[#6c6c6c]">{message}</p><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={onCancel}>إلغاء</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></div></div></div>; }
