"use client";

import { FormEvent, useState } from "react";
import { Edit3, Plus, Trash2, X } from "lucide-react";
import { Button, Card, ConfirmDialog, PageTitle } from "@/components/centman-shell";
import { Course, Enrollment, Student, Teacher, money, today } from "@/lib/centman-store";

type Data = { students: Student[]; teachers: Teacher[]; courses: Course[]; enrollments: Enrollment[] };
type Props = { data: Data; update: (data: Data, message?: string) => void };

export function CourseManagement({ data, update }: Props) {
  const [tab, setTab] = useState<"مادة" | "باقة">("مادة");
  const [courseEditor, setCourseEditor] = useState<Course | null>(null);
  const [enrollmentOpen, setEnrollmentOpen] = useState(false);
  const [deleteCourse, setDeleteCourse] = useState<Course | null>(null);
  const [rosterCourse, setRosterCourse] = useState<Course | null>(null);
  const [query, setQuery] = useState("");
  const [teacherFilter, setTeacherFilter] = useState("all");
  const [sortBy, setSortBy] = useState<"name" | "price" | "enrolled">("name");
  const enrolledCount = (courseId: number) => data.enrollments.filter(enrollment => enrollment.courseId === courseId && enrollment.status === "نشط").length;
  const visibleCourses = data.courses
    .filter(course => course.type === tab)
    .filter(course => `${course.name} ${course.teacher}`.toLowerCase().includes(query.toLowerCase()))
    .filter(course => teacherFilter === "all" || course.teacher === teacherFilter)
    .sort((a, b) => sortBy === "price" ? b.price - a.price : sortBy === "enrolled" ? enrolledCount(b.id) - enrolledCount(a.id) : a.name.localeCompare(b.name, "ar"));
  return <>
    <PageTitle eyebrow="البرامج التعليمية" title="المواد والباقات" action={<div className="flex gap-2"><Button onClick={() => setCourseEditor({ id: 0, name: "", type: tab, teacher: "", price: 0, enrolled: 0 })}><Plus size={15} className="ml-2 inline" />إضافة {tab}</Button><Button variant="outline" onClick={() => setEnrollmentOpen(true)}><Plus size={15} className="ml-2 inline" />إضافة تسجيل</Button></div>} />
    <div className="mb-5 flex flex-wrap gap-2"><button onClick={() => setTab("مادة")} className={`rounded-xl px-5 py-2.5 text-xs font-bold ${tab === "مادة" ? "bg-[#5054c0] text-white" : "bg-white text-[#6c6c6c]"}`}>المواد</button><button onClick={() => setTab("باقة")} className={`rounded-xl px-5 py-2.5 text-xs font-bold ${tab === "باقة" ? "bg-[#5054c0] text-white" : "bg-white text-[#6c6c6c]"}`}>الباقات</button></div>
    <div className="mb-5 grid gap-2 md:grid-cols-[1fr_auto_auto]"><input value={query} onChange={event => setQuery(event.target.value)} placeholder="ابحث بالاسم أو الأستاذ..." className="rounded-xl border border-[#dce7df] bg-white px-3 py-2.5 text-xs outline-none focus:border-[#5054c0]" /><select value={teacherFilter} onChange={event => setTeacherFilter(event.target.value)} className="rounded-xl border border-[#dce7df] bg-white px-3 py-2.5 text-xs outline-none"><option value="all">كل الأساتذة</option>{data.teachers.map(teacher => <option key={teacher.id} value={teacher.name}>{teacher.name}</option>)}</select><select value={sortBy} onChange={event => setSortBy(event.target.value as typeof sortBy)} className="rounded-xl border border-[#dce7df] bg-white px-3 py-2.5 text-xs outline-none"><option value="name">ترتيب: الاسم</option><option value="price">ترتيب: السعر</option><option value="enrolled">ترتيب: عدد المسجلين</option></select></div>
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{visibleCourses.map(course => <Card key={course.id}><div className="mb-5 flex items-start justify-between"><span className="rounded-lg bg-[#e4e8fd] px-2 py-1 text-[10px] font-bold text-[#3a3b9b]">{course.type}</span><div className="flex gap-2"><button aria-label="تعديل" onClick={() => setCourseEditor(course)} className="rounded-lg bg-[#e4e8fd] p-2 text-[#5054c0]"><Edit3 size={14} /></button><button aria-label="حذف" onClick={() => setDeleteCourse(course)} className="rounded-lg bg-[#faf4de] p-2 text-[#a08500]"><Trash2 size={14} /></button></div></div><h3 className="text-lg font-black text-[#292929]">{course.name}</h3>{course.type === "باقة" ? <div className="mt-2 space-y-1 text-xs text-[#6c6c6c]">{(course.subjectIds || []).map(subjectId => { const subject = data.courses.find(item => item.id === subjectId); return subject ? <p key={subject.id}>{subject.name} • {subject.teacher || "لم يحدد أستاذ"}</p> : null; })}{!course.subjectIds?.length && <p>لم تتم إضافة مواد للباقة</p>}</div> : <p className="mt-2 text-xs text-[#6c6c6c]">{course.teacher || "لم يحدد أستاذ"}</p>}<div className="mt-5 flex justify-between border-t border-[#f1f1f1] pt-4 text-xs"><button type="button" onClick={() => setRosterCourse(course)} className="font-bold text-[#5054c0] underline decoration-[#c7caf4] underline-offset-4 hover:text-[#3a3b9b]">{enrolledCount(course.id)} طالب مسجل</button><b className="text-[#5054c0]">{money(course.price)}</b></div></Card>)}</div>
    {!visibleCourses.length && <Card><div className="py-12 text-center text-sm text-[#6c6c6c]">لا توجد عناصر في هذا التصنيف</div></Card>}
    {courseEditor && <CourseModal course={courseEditor} teachers={data.teachers} subjects={data.courses.filter(item => item.type === "مادة")} onClose={() => setCourseEditor(null)} onSave={course => { const courses = course.id ? data.courses.map(item => item.id === course.id ? course : item) : [...data.courses, { ...course, id: Date.now() }]; update({ ...data, courses }, "تم حفظ المادة أو الباقة"); setCourseEditor(null); }} />}
    {enrollmentOpen && <EnrollmentModal students={data.students} courses={data.courses} enrollments={data.enrollments} onClose={() => setEnrollmentOpen(false)} onSave={enrollment => { if (data.enrollments.some(item => item.studentId === enrollment.studentId && item.courseId === enrollment.courseId && item.status === "نشط")) return; update({ ...data, enrollments: [...data.enrollments, { ...enrollment, id: Date.now() }] }, "تمت إضافة التسجيل"); setEnrollmentOpen(false); }} />}
    {rosterCourse && <RosterModal course={rosterCourse} students={data.students.filter(student => data.enrollments.some(enrollment => enrollment.courseId === rosterCourse.id && enrollment.studentId === student.id && enrollment.status === "نشط"))} onClose={() => setRosterCourse(null)} />}
    {deleteCourse && <ConfirmDialog title="تأكيد حذف المادة أو الباقة" message={`هل أنت متأكد من حذف ${deleteCourse.name}؟ سيتم حذف التسجيلات المرتبطة بها أيضاً.`} onCancel={() => setDeleteCourse(null)} onConfirm={() => { update({ ...data, courses: data.courses.filter(item => item.id !== deleteCourse.id), enrollments: data.enrollments.filter(item => item.courseId !== deleteCourse.id) }, "تم حذف الدورة والتسجيلات المرتبطة"); setDeleteCourse(null); }} />}
  </>;
}

function CourseModal({ course, teachers, subjects, onClose, onSave }: { course: Course; teachers: Teacher[]; subjects: Course[]; onClose: () => void; onSave: (course: Course) => void }) { const [form, setForm] = useState({ ...course, price: String(course.price) }); const [subjectIds, setSubjectIds] = useState<number[]>(course.subjectIds || []); const submit = (event: FormEvent) => { event.preventDefault(); onSave({ ...form, price: Number(form.price), teacher: form.type === "باقة" ? "" : form.teacher, subjectIds: form.type === "باقة" ? subjectIds : undefined }); }; return <Modal title={course.id ? "تعديل المادة أو الباقة" : "إضافة مادة أو باقة"} onClose={onClose}><form onSubmit={submit} className="space-y-4"><Field label="الاسم" value={form.name} onChange={name => setForm({ ...form, name })} />{form.type === "مادة" ? <TeacherPicker teachers={teachers} value={form.teacher} onChange={teacher => setForm({ ...form, teacher })} /> : <div className="rounded-xl border border-[#e5e5e5] bg-[#f7f7f7] p-4"><p className="mb-3 text-xs font-bold text-[#6c6c6c]">مواد الباقة والأساتذة</p><div className="space-y-2">{subjects.map(subject => <label key={subject.id} className="flex items-center justify-between rounded-lg bg-white p-3 text-xs"><span><b>{subject.name}</b><small className="mr-2 text-[#8a8a8a]">{subject.teacher || "لم يحدد أستاذ"}</small></span><input type="checkbox" checked={subjectIds.includes(subject.id)} onChange={() => setSubjectIds(current => current.includes(subject.id) ? current.filter(id => id !== subject.id) : [...current, subject.id])} className="h-4 w-4 accent-[#5054c0]" /></label>)}{!subjects.length && <p className="text-xs text-[#a08500]">أنشئ المواد أولاً قبل إنشاء الباقة.</p>}</div></div>}<Field label="السعر (MAD)" type="number" value={form.price} onChange={price => setForm({ ...form, price })} /><div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>إلغاء</Button><Button type="submit" disabled={form.type === "باقة" && !subjectIds.length}>حفظ</Button></div></form></Modal>; }

function TeacherPicker({ teachers, value, onChange }: { teachers: Teacher[]; value: string; onChange: (teacher: string) => void }) { const [query, setQuery] = useState(value); const [open, setOpen] = useState(false); const filtered = teachers.filter(teacher => `${teacher.name} ${teacher.specialty}`.toLowerCase().includes(query.toLowerCase())); return <div className="relative text-right"><span className="mb-2 block text-xs font-bold text-[#6c6c6c]">الأستاذ</span><input required value={query} onFocus={() => setOpen(true)} onChange={event => { setQuery(event.target.value); setOpen(true); }} placeholder="ابحث عن أستاذ..." className="w-full rounded-xl border border-[#e5e5e5] bg-[#f7f7f7] px-3 py-2.5 text-sm outline-none focus:border-[#5054c0]" />{open && <><button type="button" aria-label="إغلاق قائمة الأساتذة" className="fixed inset-0 z-10 cursor-default" onClick={() => setOpen(false)} /><div className="absolute right-0 top-full z-20 mt-2 max-h-48 w-full overflow-y-auto rounded-xl border border-[#e5e5e5] bg-white p-2 shadow-xl">{filtered.length ? filtered.map(teacher => <button type="button" key={teacher.id} onClick={() => { onChange(teacher.name); setQuery(teacher.name); setOpen(false); }} className="block w-full rounded-lg px-3 py-2 text-right text-xs hover:bg-[#e4e8fd]"><b className="block text-[#292929]">{teacher.name}</b><span className="text-[#6c6c6c]">{teacher.specialty} • {teacher.commission}%</span></button>) : <p className="p-3 text-xs text-[#6c6c6c]">لا يوجد أستاذ مطابق</p>}</div></>}</div>; }

function EnrollmentModal({ students, courses, enrollments, onClose, onSave }: { students: Student[]; courses: Course[]; enrollments: Enrollment[]; onClose: () => void; onSave: (enrollment: Omit<Enrollment, "id">) => void }) { const [studentId, setStudentId] = useState(students[0]?.id || 0); const [courseId, setCourseId] = useState(courses[0]?.id || 0); const available = courses.filter(course => !enrollments.some(enrollment => enrollment.studentId === studentId && enrollment.courseId === course.id && enrollment.status === "نشط")); return <Modal title="إضافة تسجيل جديد" onClose={onClose}><form onSubmit={event => { event.preventDefault(); onSave({ studentId, courseId, enrolledAt: today, status: "نشط" }); }} className="space-y-4"><label className="block text-right"><span className="mb-2 block text-xs font-bold text-[#6c6c6c]">اختر الطالب</span><select value={studentId} onChange={event => setStudentId(Number(event.target.value))} className="w-full rounded-xl border border-[#e5e5e5] bg-white p-3 text-sm">{students.map(student => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label className="block text-right"><span className="mb-2 block text-xs font-bold text-[#6c6c6c]">اختر المادة أو الباقة</span><select value={courseId} onChange={event => setCourseId(Number(event.target.value))} className="w-full rounded-xl border border-[#e5e5e5] bg-white p-3 text-sm">{available.map(course => <option key={course.id} value={course.id}>{course.name} • {course.type} • {money(course.price)}</option>)}</select></label>{!available.length && <p className="text-xs font-bold text-[#a08500]">هذا الطالب مسجل في جميع المواد والباقات المتاحة.</p>}<div className="flex justify-end gap-2"><Button variant="outline" onClick={onClose}>إلغاء</Button><Button type="submit" disabled={!available.length}>إضافة التسجيل</Button></div></form></Modal>; }

function RosterModal({ course, students, onClose }: { course: Course; students: Student[]; onClose: () => void }) { return <Modal title={`الطلاب المسجلون في ${course.name}`} onClose={onClose}><div className="space-y-3">{students.length ? students.map(student => <div key={student.id} className="flex items-center justify-between rounded-xl border border-[#f0f0f0] bg-[#fafafa] p-3 text-right"><div><p className="font-bold text-[#292929]">{student.name}</p><p className="mt-1 text-xs text-[#6c6c6c]">{student.phone || "لا يوجد رقم هاتف"}</p></div><span className="rounded-full bg-[#e4f5eb] px-2.5 py-1 text-[10px] font-bold text-[#218653]">نشط</span></div>) : <p className="rounded-xl bg-[#fafafa] p-6 text-center text-sm text-[#6c6c6c]">لا يوجد طلاب مسجلون حالياً</p>}</div></Modal>; }

function Field({ label, value, onChange, type = "text" }: { label: string; value: string | number; onChange: (value: string) => void; type?: string }) { return <label className="block text-right"><span className="mb-2 block text-xs font-bold text-[#6c6c6c]">{label}</span><input required type={type} value={value} onChange={event => onChange(event.target.value)} className="w-full rounded-xl border border-[#e5e5e5] bg-[#f7f7f7] px-3 py-2.5 text-sm outline-none focus:border-[#5054c0]" /></label>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-40 flex items-center justify-center bg-[#292929]/30 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-black text-[#292929]">{title}</h3><button onClick={onClose} className="text-[#6c6c6c]"><X size={19} /></button></div>{children}</div></div>; }
