import { NextResponse } from "next/server";
import { normalizeRole, passwordHash, requireUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export async function GET() { try { const user = await requireUser(); if (user.role !== "SUPER_ADMIN") return NextResponse.json({ error: "Super-admin access required" }, { status: 403 }); return NextResponse.json(await prisma.user.findMany({ select: { id: true, name: true, username: true, role: true, active: true, createdAt: true }, orderBy: { createdAt: "asc" } })); } catch (error) { return NextResponse.json({ error: error instanceof Error && error.message === "UNAUTHORIZED" ? "Unauthorized" : "Unable to load users" }, { status: error instanceof Error && error.message === "UNAUTHORIZED" ? 401 : 500 }); } }

export async function POST(request: Request) { try { const user = await requireUser(); if (user.role !== "SUPER_ADMIN") return NextResponse.json({ error: "Super-admin access required" }, { status: 403 }); const body = await request.json(); const name = String(body.name || "").trim(); const username = String(body.username || "").trim().toLowerCase(); const requestedRole = String(body.role || "ADMIN").trim(); if (!name || !username || !body.password) return NextResponse.json({ error: "All fields are required" }, { status: 400 }); if (requestedRole !== "ADMIN" && requestedRole !== "SUPER_ADMIN") return NextResponse.json({ error: "Invalid account role" }, { status: 400 }); const role = normalizeRole(requestedRole); const created = await prisma.user.create({ data: { name, username, passwordHash: passwordHash(String(body.password)), role } }); return NextResponse.json({ id: created.id, name: created.name, username: created.username, role: created.role }, { status: 201 }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to create account" }, { status: 500 }); } }

export async function PATCH(request: Request) { try { const user = await requireUser(); if (user.role !== "SUPER_ADMIN") return NextResponse.json({ error: "Super-admin access required" }, { status: 403 }); const body = await request.json(); const id = Number(body.id); if (!Number.isInteger(id)) return NextResponse.json({ error: "Invalid user id" }, { status: 400 }); if (id === user.id && body.active === false) return NextResponse.json({ error: "You cannot deactivate your own account" }, { status: 400 }); const data: { name?: string; role?: string; active?: boolean; passwordHash?: string } = {}; if (body.name !== undefined) { const name = String(body.name).trim(); if (!name) return NextResponse.json({ error: "Name is required" }, { status: 400 }); data.name = name; } if (body.role !== undefined) { const role = String(body.role).trim(); if (role !== "ADMIN" && role !== "SUPER_ADMIN") return NextResponse.json({ error: "Invalid account role" }, { status: 400 }); data.role = normalizeRole(role); } if (body.active !== undefined) { if (typeof body.active !== "boolean") return NextResponse.json({ error: "Invalid active state" }, { status: 400 }); data.active = body.active; } if (body.password !== undefined) { if (!String(body.password)) return NextResponse.json({ error: "Password is required" }, { status: 400 }); data.passwordHash = passwordHash(String(body.password)); } const updated = await prisma.user.update({ where: { id }, data }); if (body.active === false || body.password !== undefined) await prisma.authSession.deleteMany({ where: { userId: id } }); return NextResponse.json({ id: updated.id, name: updated.name, username: updated.username, role: updated.role, active: updated.active }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update account" }, { status: 500 }); } }
